### PR TITLE
Ft route

### PR DESCRIPTION
**Pull request by Imaraika**
#### What does this PR do?
- Auto-generate Route name based on the selected Bus Stations/Stops
- Validate Create Route Endpoint to ensure that duplicated routes are not created.
#### Description of Task to be completed?
- A Routename should be auto generate according to the selected busstop
- Route should no be assigned a busstop that is not exist
#### How should this be manually tested?
-  Using postman, try to use busstopid which does not exist will give you an error.
- Using valid id will have a successful result
#### Any background context you want to provide?
- A Route name should be assigned a valid busstopids on creation
#### What are the relevant Trello boards stories?
https://trello.com/c/qfcOKI77/114-auto-generate-route-names-base-on-the-combined-bus-stop-names
#### Questions:

### CODE REVIEW

**Review by Isaackomeza — CHANGES_REQUESTED** [review]
@Imaraika  Can you remove those commenting lines and do rebase to have up to date codes?

**Comment by Imaraika** [comment]
> @Imaraika Can you remove those commenting lines and do rebase to have up to date codes?

Yes Yes Isaac I worked on it ! Thanks

**Review by Isaackomeza — APPROVED** [review]

**Review by Rwandarushya — COMMENTED** [review]
Please remove the comments lines in the route controller

**Comment by Imaraika** [comment]
> Please remove the comments lines in the route controller

Yes Yes Marius ! I removed them ! Thanks

**Pull request merged**
