### PR TITLE
update swagger documentation file

### PR DESCRIPTION
**Pull request by giranezafiacre**
#### Screenshots (if appropriate)
swaggerPR

### CODE REVIEW

**Comment by giranezafiacre** [comment]
[Integrate Swagger Documentation](https://trello.com/c/dItnOjAE/122-integrate-swagger-documentation)

**Review by Isaackomeza — CHANGES_REQUESTED** [review]
Thank you @giranezafiacre, you did a great job. 
However, I think you can add a `POST /api/users/signup` endpoint for an admin user to create a new bus user

**Comment by giranezafiacre** [comment]
@Isaackomeza you told me that a user/admin will be created at time of running project so I thought that there is no need to do signup

**Comment by giranezafiacre** [comment]
@Isaackomeza you told me that a user/admin will be created at time of running project so I thought that there is no need to do signup

**Comment by Isaackomeza** [comment]
> @Isaackomeza you told me that a user/admin will be created at time of running project so I thought that there is no need to do signup

Yes, @giranezafiacre For admin there is no need to create admin user but there is also a bus user who need to be created by admin

**Comment by giranezafiacre** [comment]
> Thank you @giranezafiacre, you did a great job.
> However, I think you can add a `POST /api/users/signup` endpoint for an admin user to create a new bus user

**Pull request merged**
