### PR TITLE
added routeData atribute to stores GeoJson Data

### PR DESCRIPTION
**Pull request by Rwandarushya**
#### What does this PR do?
-save routedata (coordinates) from mapBox Api
#### Description of Task to be completed?
-when  you are creating new route, you should get route imformation like geometry, distance from mapBox Api 
- the Api will use the origin's coordinates and destination's cordinates to find all other information related to that route
#### How should this be manually tested?
-this can be tested by creating new route in postman and providing valid id for both origin and validation
#### Any background context you want to provide?
N/A
#### What are the relevant Trello boards stories?
N/A
#### Screenshots (if appropriate)
N/A
#### Questions:
N/Q

### CODE REVIEW

**Review by Isaackomeza — COMMENTED** [review]
Thank you @Rwandarushya You did a great job, But I would suggest if Possible to seed this geometry data if you can. I think it can also be good

**Comment by Rwandarushya** [comment]
> Thank you @Rwandarushya You did a great job, But I would suggest if Possible to seed this geometry data if you can. I think it can also be good

Ok, that is a great idea, i will be using the same data for route seeders

**Review by Imaraika — COMMENTED** [review]
Well Done Marius I have seen You've added a routeData attribute to store GeoJson data it is storing the data as well.

**Review by Imaraika — APPROVED** [review]

**Review by fistonhn — APPROVED** [review]

**Comment by fistonhn** [comment]
I approved this PR because he has done with the feedbacks that I gave during the call which I made with him at 2 PM.

**Pull request merged**
