### PR TITLE
Fx structure

### PR DESCRIPTION
**Pull request by Rwandarushya**
#### What does this PR do?
-added build script into package.json folder, this file will create a build folder that will have our babel converted code for deployment purpose

- added procfile for heroku deployment

-added .eslintignore file to ignore the build folder because it included the old javascript(converted by babel) code.

-added code to test if database is  connected

#### Description of Task to be completed?
N/A
#### How should this be manually tested?
N/A
#### Any background context you want to provide?
N/A
#### What are the relevant pivotal tracker stories?
N/A
#### Screenshots (if appropriate)
N/A
#### Questions:
is it ok to ignore the eslint for the build folder?

### CODE REVIEW

**Comment by fistonhn** [comment]
Marius you did a great job. However I can suggest you to follow eslint rules if you have a time for it as like we have a lot to do this week. You can see red symbols there which should be removed.
Screenshot_20200929-152112

**Review by Isaackomeza — COMMENTED** [review]
Good work! for your question, I think there is no problem of ignoring eslint in build Forder because it is there to help us during development to make our code clean with minimal errors

**Comment by Rwandarushya** [comment]
> Marius you did a great job. However I can suggest you to follow eslint rules if you have a time for it as like we have a lot to do this week. You can see red symbols there which should be removed.
> Screenshot_20200929-152112

**Comment by Rwandarushya** [comment]
Thanks for your comment Fiston but the above eslint errors are coming from build folder which is generated by babel

**Pull request closed without merging**
